### ISSUE TITLE
ConsoleWidget(): `RuntimeError: You can't initialize an object twice!` with traitlets master

### ISSUE THREAD

**Issue by pankajp** [jupyter/qtconsole#104]
```
from qtconsole.qt import QtGui
from qtconsole.console_widget import ConsoleWidget
QtGui.QApplication.instance() or QtGui.QApplication([])
cw = ConsoleWidget()
```
Results in 
```
Traceback (most recent call last):
  File "../../canopy-jupyter/scratch.py", line 4, in <module>
    cw = ConsoleWidget()
  File "/home/pankaj/work/enthought/jupyter/qtconsole/qtconsole/console_widget.py", line 214, in __init__
    LoggingConfigurable.__init__(self, **kw)
  File "/home/pankaj/work/enthought/jupyter/traitlets/traitlets/config/configurable.py", line 74, in __init__
    super(Configurable, self).__init__(**kwargs)
  File "/home/pankaj/work/enthought/jupyter/traitlets/traitlets/traitlets.py", line 946, in __init__
    super(HasTraits, self).__init__()
RuntimeError: You can't initialize an object twice!
```
with traitlets master. This is because of mixing old-style and `__init__` call and `super` `__init__` call.
Simple `git bisect` indicated the causal commit to be: https://github.com/ipython/traitlets/pull/174

A solution would be to do things similar to `SuperQObject` https://github.com/jupyter/qtconsole/blob/master/qtconsole/util.py#L48 , i.e. a `SuperQWidget`, and probably any other `Super` qobject subclass which needs to be used in multiple inheritance with HasTraits.

**Comment by pshchelo** [comment]
Due to this, I **can not start** latest Qtconsole at all.

Clean virtualenv, no custom `~/.jupyter/jupyter_*_config.py` files.

```
$ pip install jupyter pyside
...
$ pip freeze
backports-abc==0.4
backports.ssl-match-hostname==3.5.0.1
certifi==2016.2.28
decorator==4.0.9
functools32==3.2.3.post2
ipykernel==4.3.1
ipython==4.1.2
ipython-genutils==0.1.0
ipywidgets==4.1.1
Jinja2==2.8
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.2.2
jupyter-console==4.1.1
jupyter-core==4.1.0
MarkupSafe==0.23
mistune==0.7.2
nbconvert==4.1.0
nbformat==4.0.1
notebook==4.1.0
path.py==8.1.2
pexpect==4.0.1
pickleshare==0.6
ptyprocess==0.5.1
Pygments==2.1.3
PySide==1.2.4
pyzmq==15.2.0
qtconsole==4.2.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
terminado==0.6
tornado==4.3
traitlets==4.2.1

$ jupyter qtconsole

Traceback (most recent call last):
  File "/home/pshchelo/.virtualenvs/ipynb/bin/jupyter-qtconsole", line 11, in <module>
    sys.exit(main())
  File "/home/pshchelo/.virtualenvs/ipynb/local/lib/python2.7/site-packages/qtconsole/qtconsoleapp.py", line 396, in main
    JupyterQtConsoleApp.launch_instance()
  File "/home/pshchelo/.virtualenvs/ipynb/local/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/pshchelo/.virtualenvs/ipynb/local/lib/python2.7/site-packages/traitlets/config/application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-115>", line 2, in initialize
  File "/home/pshchelo/.virtualenvs/ipynb/local/lib/python2.7/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/pshchelo/.virtualenvs/ipynb/local/lib/python2.7/site-packages/qtconsole/qtconsoleapp.py", line 368, in initialize
    self.init_qt_elements()
  File "/home/pshchelo/.virtualenvs/ipynb/local/lib/python2.7/site-packages/qtconsole/qtconsoleapp.py", line 250, in init_qt_elements
    local_kernel=local_kernel)
  File "/home/pshchelo/.virtualenvs/ipynb/local/lib/python2.7/site-packages/qtconsole/rich_jupyter_widget.py", line 53, in __init__
    super(RichJupyterWidget, self).__init__(*args, **kw)
  File "/home/pshchelo/.virtualenvs/ipynb/local/lib/python2.7/site-packages/qtconsole/jupyter_widget.py", line 112, in __init__
    super(JupyterWidget, self).__init__(*args, **kw)
  File "/home/pshchelo/.virtualenvs/ipynb/local/lib/python2.7/site-packages/qtconsole/frontend_widget.py", line 181, in __init__
    super(FrontendWidget, self).__init__(*args, **kw)
  File "/home/pshchelo/.virtualenvs/ipynb/local/lib/python2.7/site-packages/qtconsole/history_console_widget.py", line 28, in __init__
    super(HistoryConsoleWidget, self).__init__(*args, **kw)
  File "/home/pshchelo/.virtualenvs/ipynb/local/lib/python2.7/site-packages/qtconsole/console_widget.py", line 211, in __init__
    LoggingConfigurable.__init__(self, **kw)
  File "/home/pshchelo/.virtualenvs/ipynb/local/lib/python2.7/site-packages/traitlets/config/configurable.py", line 74, in __init__
    super(Configurable, self).__init__(**kwargs)
  File "/home/pshchelo/.virtualenvs/ipynb/local/lib/python2.7/site-packages/traitlets/traitlets.py", line 954, in __init__
    super(HasTraits, self).__init__(*super_args, **super_kwargs)
RuntimeError: You can't initialize an object twice!
```

**Comment by pshchelo** [comment]
Downgrading traitlets to traitlets==4.1.0 solves the issue.

**Comment by ccordoba12** [comment]
@minrk, this seems an important issue. Should it be fixed here or in traitlets?

**Comment by minrk** [comment]
Probably both. I'll look into it.

**Comment by ccordoba12** [comment]
Thanks Min! :+1:

**Comment by minrk** [comment]
I have at least narrowed this down to something PySide does differently from PyQt, since it's working without issue on PyQt.

**Comment by minrk** [comment]
I opened #114, which seems to fix this.
