### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by Rainer88** [jupyter/qtconsole#105]
```
> `Traceback (most recent call last):
>   File "C:\Anaconda2\Scripts\jupyter-console-script.py", line 4, in <module>
>     app.main()
>   File "C:\Anaconda2\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
>     return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
>   File "C:\Anaconda2\lib\site-packages\traitlets\config\application.py", line 588, in launch_instance
>     app.initialize(argv)
>   File "<decorator-gen-115>", line 2, in initialize
>   File "C:\Anaconda2\lib\site-packages\traitlets\config\application.py", line 74, in catch_config_error
>     return method(app, *args, **kwargs)
>   File "C:\Anaconda2\lib\site-packages\jupyter_console\app.py", line 136, in initialize
>     self.init_shell()
>   File "C:\Anaconda2\lib\site-packages\jupyter_console\app.py", line 103, in init_shell
>     JupyterConsoleApp.initialize(self)
>   File "C:\Anaconda2\lib\site-packages\jupyter_client\consoleapp.py", line 329, in initialize
>     self.init_kernel_manager()
>   File "C:\Anaconda2\lib\site-packages\jupyter_client\consoleapp.py", line 283, in init_kernel_manager
>     self.kernel_manager.start_kernel(**kwargs)
>   File "C:\Anaconda2\lib\site-packages\jupyter_client\manager.py", line 244, in start_kernel
>     **kw)
>   File "C:\Anaconda2\lib\site-packages\jupyter_client\manager.py", line 190, in _launch_kernel
>     return launch_kernel(kernel_cmd, **kw)
>   File "C:\Anaconda2\lib\site-packages\jupyter_client\launcher.py", line 108, in launch_kernel
>     proc = Popen(cmd, **kwargs)
>   File "C:\Anaconda2\lib\subprocess.py", line 710, in __init__
>     errread, errwrite)
>   File "C:\Anaconda2\lib\subprocess.py", line 958, in _execute_child
>     startupinfo)
> WindowsError: [Error 2] The system cannot find the file specified`
```

I am getting the above error in anaconda, I've tried uninstalling it numerous times hoping for a different result.. Is there any way to help find the problem?  I have no idea where to start.

**Comment by minrk** [comment]
What do you get from `jupyter kernelspec list`?

**Comment by Rainer88** [comment]
I get the following

```
Available kernels:
  python2    C:\ProgramData\jupyter\kernels\python2
  python3    C:\ProgramData\jupyter\kernels\python3
```

**Comment by takluyver** [comment]
Have a look in those folder locations for a kernel.json file. Inside it, the first item in argv should be a path ending in `python.exe`. What path is it, and does it exist?

**Comment by Rainer88** [comment]
Great! That worked... the path in the kernel.json file was incorrect.

Thank you!!
