### ISSUE TITLE
Building into an exectuable with Py2App causes "No module named cython"

### ISSUE THREAD

**Issue by ronpandolfi** [jupyter/qtconsole#120]
I am trying to build a qtconsole RichJupyterWidget into a .exe using Py2App. This causes an ImportError: No module named cython. Despite the error message, Cython is included in the resulting library.zip.

See attached a minimal example of what does not work for me.

My version info is listed below:
```
{'commit_hash': u'b573435',
 'commit_source': 'installation',
 'default_encoding': 'cp437',
 'ipython_path': 'C:\\Python27\\lib\\site-packages\\IPython',
 'ipython_version': '4.1.2',
 'os_name': 'nt',
 'platform': 'Windows-10-10.0.10586',
 'sys_executable': 'C:\\Python27\\python.exe',
 'sys_platform': 'win32',
 'sys_version': '2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]'}

backports-abc==0.4
backports.ssl-match-hostname==3.5.0.1
certifi==2016.2.28
configparser==3.3.0.post2
cx-Freeze==4.3.4
cycler==0.10.0
Cython==0.23.4
decorator==4.0.9
entrypoints==0.2
et-xmlfile==1.0.1
fabio==0.3.0
functools32==3.2.3.post2
h5py==2.5.0
ipykernel==4.3.1
ipython==4.1.2
ipython-genutils==0.1.0
ipywidgets==4.1.1
jdcal==1.2
Jinja2==2.8
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.2.2
jupyter-console==4.1.1
jupyter-core==4.1.0
MarkupSafe==0.23
matplotlib==1.5.1
mistune==0.7.2
nbconvert==4.2.0
nbformat==4.0.1
nexusformat==0.2.2
notebook==4.1.0
numpy==1.10.4
openpyxl==2.3.4
path.py==8.1.2
pathlib2==2.1.0
pickleshare==0.7.2
Pillow==3.1.1
pyFAI==0.11.0
pyfits==3.4
pyglet==1.2.4
Pygments==2.1.3
PyOpenGL==3.1.0
pyparsing==2.1.1
pyqtgraph==0.9.10
pyreadline==2.1
PySide==1.2.4
python-dateutil==2.5.2
pytz==2016.3
PyYAML==3.11
pyzmq==15.2.0
QDarkStyle==2.1
qtconsole==4.2.1
scipy==0.17.0
Shiboken==1.2.2
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
tornado==4.3
traitlets==4.2.1
```

[jupitertest.zip](https://github.com/jupyter/qtconsole/files/218165/jupitertest.zip)

**Comment by minrk** [comment]
qtconsole doesn't require Cython, so it's unlikely that there would be anything relevant to QtConsole going on. My guess is that Py2App doesn't correctly identify Cython files (I believe Cython provides both a `Cython/` directory and `cython.py`).

**Comment by ronpandolfi** [comment]
Hi mnirk, thanks for the response! I do see a `Cython` directory and a `cython.pyc` in the `library.zip`; there are also `Cython.Compiler.*.pyd` files in the build directory. 

I tried putting `import cython` as the first line of my `main.py` as a test to see if cython is correctly copied into the build (in an attempt to force the same error earlier). This does not cause an error; instead the same import error occurs on `from qtconsole.rich_jupyter_widget import RichJupyterWidget`.

Below is the traceback showing this:

```
---------------------------
cx_Freeze: Python error in main script
---------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
    exec(code, m.__dict__)
  File "main.py", line 18, in <module>
  File "C:\Python27\lib\site-packages\qtconsole\rich_jupyter_widget.py", line 14, in <module>
    from .jupyter_widget import JupyterWidget
  File "C:\Python27\lib\site-packages\qtconsole\jupyter_widget.py", line 21, in <module>
    from .frontend_widget import FrontendWidget
  File "C:\Python27\lib\site-packages\qtconsole\frontend_widget.py", line 22, in <module>
    from qtconsole.base_frontend_mixin import BaseFrontendMixin
  File "C:\Python27\lib\site-packages\qtconsole\base_frontend_mixin.py", line 3, in <module>
    from jupyter_client import BlockingKernelClient
  File "C:\Python27\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "C:\Python27\lib\site-packages\jupyter_client\connect.py", line 21, in <module>
    import zmq
  File "C:\Python27\lib\site-packages\zmq\__init__.py", line 66, in <module>
    from zmq import backend
  File "C:\Python27\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Python27\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Python27\lib\site-packages\zmq\backend\select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
ImportError: No module named cython

---------------------------
OK   
---------------------------

```

This may not be relevant, but looking at the zmq package I have installed I see a slew of Python 3 syntax even though this is on 2.7. Is that to be expected?

**Comment by minrk** [comment]
There should be a zmq/backend/cython/ directory full of compiled extensions. Does that exist?

As for the syntax errors, there are a couple of asyncio modules in pyzmq that only work on Python 3. There's no problem with them being present on Python 2, but they can't be imported.

**Comment by ronpandolfi** [comment]
You were right! Cx_freeze missed it. The below SO post provided the precise solution. Thanks for the help!

http://stackoverflow.com/questions/25180032/how-do-i-make-pyzmq-14-3-1-and-cx-freeze-4-3-3-work-together
