### ISSUE TITLE
qtconsole does not work with pyqt5 5.11 ("ModuleNotFoundError: No module named 'sip'")

### ISSUE THREAD

**Issue by nonZero** [jupyter/qtconsole#291]
On a fresh windows machine with python 3.7.0, after installing the following:

    pip install ipython notebook qtconsole pyqt5

Running `ipython qtconsole` opens an `Error startin QtConsole` dialog with the following error:

```
---------------------------
Error starting QtConsole
---------------------------
Traceback (most recent call last):
  File "c:\users\ieuser\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\ieuser\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\IEUser\AppData\Local\Programs\Python\Python37-32\Scripts\ipython.exe\__main__.py", line 9, in <module>
    sys.exit(start_ipython())
  File "c:\users\ieuser\appdata\local\programs\python\python37-32\lib\site-packages\IPython\__init__.py", line 125, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "c:\users\ieuser\appdata\local\programs\python\python37-32\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-113>", line 2, in initialize
  File "c:\users\ieuser\appdata\local\programs\python\python37-32\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\users\ieuser\appdata\local\programs\python\python37-32\lib\site-packages\IPython\terminal\ipapp.py", line 308, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "c:\users\ieuser\appdata\local\programs\python\python37-32\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\users\ieuser\appdata\local\programs\python\python37-32\lib\site-packages\IPython\core\application.py", line 450, in initialize
    self.parse_command_line(argv)
  File "c:\users\ieuser\appdata\local\programs\python\python37-32\lib\site-packages\IPython\terminal\ipapp.py", line 303, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "c:\users\ieuser\appdata\local\programs\python\python37-32\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\users\ieuser\appdata\local\programs\python\python37-32\lib\site-packages\traitlets\config\application.py", line 514, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "c:\users\ieuser\appdata\local\programs\python\python37-32\lib\site-packages\IPython\core\application.py", line 243, in initialize_subcommand
    return super(BaseIPythonApplication, self).initialize_subcommand(subc, argv)
  File "<decorator-gen-3>", line 2, in initialize_subcommand
  File "c:\users\ieuser\appdata\local\programs\python\python37-32\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\users\ieuser\appdata\local\programs\python\python37-32\lib\site-packages\traitlets\config\application.py", line 445, in initialize_subcommand
    subapp = import_item(subapp)
  File "c:\users\ieuser\appdata\local\programs\python\python37-32\lib\site-packages\ipython_genutils\importstring.py", line 31, in import_item
    module = __import__(package, fromlist=[obj])
  File "c:\users\ieuser\appdata\local\programs\python\python37-32\lib\site-packages\qtconsole\qtconsoleapp.py", line 60, in <module>
    from qtconsole.qt import QtCore, QtGui
  File "c:\users\ieuser\appdata\local\programs\python\python37-32\lib\site-packages\qtconsole\qt.py", line 23, in <module>
    QtCore, QtGui, QtSvg, QT_API = load_qt(api_opts)
  File "c:\users\ieuser\appdata\local\programs\python\python37-32\lib\site-packages\qtconsole\qt_loaders.py", line 365, in load_qt
    result = loaders[api]()
  File "c:\users\ieuser\appdata\local\programs\python\python37-32\lib\site-packages\qtconsole\qt_loaders.py", line 270, in import_pyqt5
    import sip
ModuleNotFoundError: No module named 'sip'
```

The same error will appear if trying to run the command:

    import sip

from a python shell, however the following works OK:

     from PyQt5 import sip

Thanks!

**Comment by nonZero** [comment]
Downgrading to pyqt5 5.10.1 solved the problem.

pyqt5 5.11 introduced some backward incompatibilities: <http://pyqt.sourceforge.net/Docs/PyQt5/incompatibilities.html#pyqt-v5-11>

**Comment by wmvanvliet** [comment]
Thanks for the report

**Comment by 392781** [comment]
Sooooo is this getting fixed any time soon?

**Comment by ccordoba12** [comment]
@392781, it's an easy fix. Would you like to submit a PR for it?

**Comment by 392781** [comment]
Not really, the cost of me trying to figure it out outweighs fixing it.  Besides I don't know where to look.

**Comment by ccordoba12** [comment]
Please look here

> File "c:\users\ieuser\appdata\local\programs\python\python37-32\lib\site-packages\qtconsole\qt_loaders.py", line 270, in import_pyqt5
    import sip

and add a try/except where the call to `import sip` is made.

**Comment by 392781** [comment]
Ok, I'll look at it tomorrow.  Thanks.

**Comment by dparvaz** [comment]
How do I downgrade my PyQt5 to 5.10.x?

**Comment by ChiChou** [comment]
> How do I downgrade my PyQt5 to 5.10.x?

`pip install pyqt5==5.10.1`
