### ISSUE TITLE
console throws error when starting kernel

### ISSUE THREAD

**Issue by chrisreddersen** [jupyter/qtconsole#309]
I upgraded spyder to 4, and when it threw the error i downgraded but with no success. I have since preformed a new clean install of anaconda(twice), and currently have spyder3.3 installed but the error remains. I am on a linux(mint) system. 3.1 had been working fine. 
An error ocurred while starting the kernel
Traceback (most recent call last):
File "/home/chris/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/home/chris/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/chris/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/__main__.py", line 11, in 
start.main()
File "/home/chris/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/start.py", line 272, in main
import_spydercustomize()
File "/home/chris/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/start.py", line 32, in import_spydercustomize
import spydercustomize
File "/home/chris/anaconda3/lib/python3.7/site‑packages/spyder_kernels/customize/spydercustomize.py", line 25, in 
from IPython.core.getipython import get_ipython
File "/home/chris/anaconda3/lib/python3.7/site‑packages/IPython/__init__.py", line 54, in 
from .core.application import Application
File "/home/chris/anaconda3/lib/python3.7/site‑packages/IPython/core/application.py", line 23, in 
from traitlets.config.application import Application, catch_config_error
File "/home/chris/anaconda3/lib/python3.7/site‑packages/traitlets/config/__init__.py", line 6, in 
from .application import *
File "/home/chris/anaconda3/lib/python3.7/site‑packages/traitlets/config/application.py", line 19, in 
from traitlets.config.configurable import Configurable, SingletonConfigurable
File "/home/chris/anaconda3/lib/python3.7/site‑packages/traitlets/config/configurable.py", line 12, in 
from .loader import Config, LazyConfigValue, _is_section_key
File "/home/chris/anaconda3/lib/python3.7/site‑packages/traitlets/config/loader.py", line 16, in 
from ipython_genutils.path import filefind
File "/home/chris/anaconda3/lib/python3.7/site‑packages/ipython_genutils/path.py", line 13, in 
import random
File "/home/chris/anaconda3/lib/python3.7/random.py", line 42, in 
from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ImportError: cannot import name 'log' from 'math' (/home/chris/math.py)
Traceback (most recent call last):
File "/home/chris/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/home/chris/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/chris/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/__main__.py", line 11, in 
start.main()
File "/home/chris/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/start.py", line 272, in main
import_spydercustomize()
File "/home/chris/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/start.py", line 32, in import_spydercustomize
import spydercustomize
File "/home/chris/anaconda3/lib/python3.7/site‑packages/spyder_kernels/customize/spydercustomize.py", line 25, in 
from IPython.core.getipython import get_ipython
File "/home/chris/anaconda3/lib/python3.7/site‑packages/IPython/__init__.py", line 54, in 
from .core.application import Application
File "/home/chris/anaconda3/lib/python3.7/site‑packages/IPython/core/application.py", line 23, in 
from traitlets.config.application import Application, catch_config_error
File "/home/chris/anaconda3/lib/python3.7/site‑packages/traitlets/config/__init__.py", line 6, in 
from .application import *
File "/home/chris/anaconda3/lib/python3.7/site‑packages/traitlets/config/application.py", line 19, in 
from traitlets.config.configurable import Configurable, SingletonConfigurable
File "/home/chris/anaconda3/lib/python3.7/site‑packages/traitlets/config/configurable.py", line 12, in 
from .loader import Config, LazyConfigValue, _is_section_key
File "/home/chris/anaconda3/lib/python3.7/site‑packages/traitlets/config/loader.py", line 16, in 
from ipython_genutils.path import filefind
File "/home/chris/anaconda3/lib/python3.7/site‑packages/ipython_genutils/path.py", line 13, in 
import random
File "/home/chris/anaconda3/lib/python3.7/random.py", line 42, in 
from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ImportError: cannot import name 'log' from 'math' (/home/chris/math.py)
Traceback (most recent call last):
File "/home/chris/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/home/chris/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/chris/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/__main__.py", line 11, in 
start.main()
File "/home/chris/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/start.py", line 272, in main
import_spydercustomize()
File "/home/chris/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/start.py", line 32, in import_spydercustomize
import spydercustomize
File "/home/chris/anaconda3/lib/python3.7/site‑packages/spyder_kernels/customize/spydercustomize.py", line 25, in 
from IPython.core.getipython import get_ipython
File "/home/chris/anaconda3/lib/python3.7/site‑packages/IPython/__init__.py", line 54, in 
from .core.application import Application
File "/home/chris/anaconda3/lib/python3.7/site‑packages/IPython/core/application.py", line 23, in 
from traitlets.config.application import Application, catch_config_error
File "/home/chris/anaconda3/lib/python3.7/site‑packages/traitlets/config/__init__.py", line 6, in 
from .application import *
File "/home/chris/anaconda3/lib/python3.7/site‑packages/traitlets/config/application.py", line 19, in 
from traitlets.config.configurable import Configurable, SingletonConfigurable
File "/home/chris/anaconda3/lib/python3.7/site‑packages/traitlets/config/configurable.py", line 12, in 
from .loader import Config, LazyConfigValue, _is_section_key
File "/home/chris/anaconda3/lib/python3.7/site‑packages/traitlets/config/loader.py", line 16, in 
from ipython_genutils.path import filefind
File "/home/chris/anaconda3/lib/python3.7/site‑packages/ipython_genutils/path.py", line 13, in 
import random
File "/home/chris/anaconda3/lib/python3.7/random.py", line 42, in 
from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ImportError: cannot import name 'log' from 'math' (/home/chris/math.py)
Traceback (most recent call last):
File "/home/chris/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/home/chris/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/chris/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/__main__.py", line 11, in 
start.main()
File "/home/chris/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/start.py", line 272, in main
import_spydercustomize()
File "/home/chris/anaconda3/lib/python3.7/site‑packages/spyder_kernels/console/start.py", line 32, in import_spydercustomize
import spydercustomize
File "/home/chris/anaconda3/lib/python3.7/site‑packages/spyder_kernels/customize/spydercustomize.py", line 25, in 
from IPython.core.getipython import get_ipython
File "/home/chris/anaconda3/lib/python3.7/site‑packages/IPython/__init__.py", line 54, in 
from .core.application import Application
File "/home/chris/anaconda3/lib/python3.7/site‑packages/IPython/core/application.py", line 23, in 
from traitlets.config.application import Application, catch_config_error
File "/home/chris/anaconda3/lib/python3.7/site‑packages/traitlets/config/__init__.py", line 6, in 
from .application import *
File "/home/chris/anaconda3/lib/python3.7/site‑packages/traitlets/config/application.py", line 19, in 
from traitlets.config.configurable import Configurable, SingletonConfigurable
File "/home/chris/anaconda3/lib/python3.7/site‑packages/traitlets/config/configurable.py", line 12, in 
from .loader import Config, LazyConfigValue, _is_section_key
File "/home/chris/anaconda3/lib/python3.7/site‑packages/traitlets/config/loader.py", line 16, in 
from ipython_genutils.path import filefind
File "/home/chris/anaconda3/lib/python3.7/site‑packages/ipython_genutils/path.py", line 13, in 
import random
File "/home/chris/anaconda3/lib/python3.7/random.py", line 42, in 
from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ImportError: cannot import name 'log' from 'math' (/home/chris/math.py)

**Comment by ccordoba12** [comment]
Closing because this error was reported in Spyder too and an answer will be provided there.
