### ISSUE TITLE
Uncaught exception in ZMQStream callback

### ISSUE THREAD

**Issue by astromancer** [jupyter/qtconsole#356]
This error seems to come up quite frequently for me. Typically after kernel restart, but sometimes also at startup via `jupyter qtconsole &`.  Manifests as an unresponsive input prompt in the qtconsole. 

Anyone else seeing this?  Sorry for the vagueness, can't reproduce this error consistently - will update when i have more.

version details:
`ipython --version`                # 7.6.1
`jupyter --version`                 # 4.4.0
`jupyter-qtconsole --version` # 4.5.2

Traceback:
```
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jupyter_client/threaded.py", line 96, in _handle_recv
    self._inspect(msg)
  File "/usr/local/lib/python3.6/dist-packages/jupyter_client/threaded.py", line 246, in _check_kernel_info_reply
    self._handle_kernel_info_reply(msg)
  File "/usr/local/lib/python3.6/dist-packages/jupyter_client/client.py", line 382, in _handle_kernel_info_reply
    adapt_version = int(msg['content']['protocol_version'].split('.')[0])
KeyError: 'protocol_version'
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 456, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 486, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jupyter_client/threaded.py", line 96, in _handle_recv
    self._inspect(msg)
  File "/usr/local/lib/python3.6/dist-packages/jupyter_client/threaded.py", line 246, in _check_kernel_info_reply
    self._handle_kernel_info_reply(msg)
  File "/usr/local/lib/python3.6/dist-packages/jupyter_client/client.py", line 382, in _handle_kernel_info_reply
    adapt_version = int(msg['content']['protocol_version'].split('.')[0])
KeyError: 'protocol_version'
ERROR:tornado.application:Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x7efea6a56f28>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 542, in <lambda>
    self.io_loop.add_callback(lambda : self._handle_events(self.socket, 0))
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 456, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 486, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jupyter_client/threaded.py", line 96, in _handle_recv
    self._inspect(msg)
  File "/usr/local/lib/python3.6/dist-packages/jupyter_client/threaded.py", line 246, in _check_kernel_info_reply
    self._handle_kernel_info_reply(msg)
  File "/usr/local/lib/python3.6/dist-packages/jupyter_client/client.py", line 382, in _handle_kernel_info_reply
    adapt_version = int(msg['content']['protocol_version'].split('.')[0])
KeyError: 'protocol_version'
```

**Comment by astromancer** [comment]
Closing since I'm no longer affected by this -- fixed by some kind of unknown dark magic!
