### ISSUE TITLE
AttributeError: module 'qtpy.QtGui' has no attribute 'QSplitter'

### ISSUE THREAD

**Issue by userfriendlyghost** [jupyter/qtconsole#415]
Hey I got an error opening qt-console and sorry for my sloppy error description

I guess it should be:
`qtpy.QtWidgets.QSplitter` instead of `qtpy.QtGui.QSplitter`

> My python-qtpy version is 1.9.0

Complete Error Message:
`
Traceback (most recent call last):
  File "/usr/bin/jupyter-qtconsole", line 11, in <module>
    load_entry_point('qtconsole==4.7.1', 'gui_scripts', 'jupyter-qtconsole')()
  File "/usr/lib/python3.8/site-packages/qtconsole/qtconsoleapp.py", line 426, in main
    JupyterQtConsoleApp.launch_instance()
  File "/usr/lib/python3.8/site-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/lib/python3.8/site-packages/traitlets/config/application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-117>", line 2, in initialize
  File "/usr/lib/python3.8/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/qtconsole/qtconsoleapp.py", line 397, in initialize
    self.init_qt_elements()
  File "/usr/lib/python3.8/site-packages/qtconsole/qtconsoleapp.py", line 274, in init_qt_elements
    self.widget = self.widget_factory(config=self.config,
  File "/usr/lib/python3.8/site-packages/qtconsole/rich_jupyter_widget.py", line 53, in __init__
    super(RichJupyterWidget, self).__init__(*args, **kw)
  File "/usr/lib/python3.8/site-packages/qtconsole/jupyter_widget.py", line 118, in __init__
    super(JupyterWidget, self).__init__(*args, **kw)
  File "/usr/lib/python3.8/site-packages/qtconsole/frontend_widget.py", line 170, in __init__
    super(FrontendWidget, self).__init__(*args, **kw)
  File "/usr/lib/python3.8/site-packages/qtconsole/history_console_widget.py", line 28, in __init__
    super(HistoryConsoleWidget, self).__init__(*args, **kw)
  File "/usr/lib/python3.8/site-packages/qtconsole/console_widget.py", line 241, in __init__
    self._splitter = QtGui.QSplitter()
`

**Comment by ccordoba12** [comment]
@dalthviz, please also address this one.
