### ISSUE TITLE
ModuleNotFoundError: No module named 'PySide' when starting jupyter qtconsole on Linux Ubuntu 18.04

### ISSUE THREAD

**Issue by AndreasLuckert** [jupyter/qtconsole#432]
When executing the `jupyter qtconsole`, the console returns:

    andylu@andylu-ThinkPad-Edge-E130:~/Desktop/Python/Scripts/General$ jupyter qtconsole
    Traceback (most recent call last):
      File "/home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/qtpy/__init__.py", line 204, in <module>
        from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
    ModuleNotFoundError: No module named 'PySide'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/linuxbrew/.linuxbrew/bin/jupyter-qtconsole", line 5, in <module>
        from qtconsole.qtconsoleapp import main
      File "/home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/qtconsole/qtconsoleapp.py", line 60, in <module>
        from qtpy import QtCore, QtGui, QtWidgets
      File "/home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/qtpy/__init__.py", line 210, in <module>
        raise PythonQtError('No Qt bindings could be found')
    qtpy.PythonQtError: No Qt bindings could be found

Next, opening the culprit `"/home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/qtpy/__init__.py", line 204`, I found this code-piece:

    if API in PYSIDE_API:
        try:
            from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
            from PySide.QtCore import __version__ as QT_VERSION  # analysis:ignore
            PYQT_VERSION = None
            PYQT5 = PYSIDE2 = False
            PYSIDE = True
        except ImportError:
            raise PythonQtError('No Qt bindings could be found')

First, I tried to play around with these import a little bit just to generate other errors, which were more cryptic so I rather returned to the original state of that script.

Then, I tried to install `pyside` without success, since `python 3.8x` (my version) doesn't support it anymore:

    andylu@andylu-ThinkPad-Edge-E130:~/Desktop/Python/Scripts/General$ pip install pyside
    Collecting pyside
      Using cached PySide-1.2.4.tar.gz (9.3 MB)
        ERROR: Command errored out with exit status 1:
         command: /home/linuxbrew/.linuxbrew/opt/python@3.8/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-29lvwdke/pyside/setup.py'"'"'; __file__='"'"'/tmp/pip-install-29lvwdke/pyside/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-dvymt0cp
             cwd: /tmp/pip-install-29lvwdke/pyside/
        Complete output (1 lines):
        only these python versions are supported: [(2, 6), (2, 7), (3, 2), (3, 3), (3, 4)]
        ----------------------------------------
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

On the other hand, I'd already installed all necessary packages (pyside2, pyqt5, etc.):

    andylu@andylu-ThinkPad-Edge-E130:~/Desktop/Python/Scripts/General$ pip install pyside2
    Requirement already satisfied: pyside2 in /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages (5.15.0)
    Requirement already satisfied: shiboken2==5.15.0 in /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages (from pyside2) (5.15.0)

    andylu@andylu-ThinkPad-Edge-E130:~/Desktop/Python/Scripts/General$ pip install pyqt5
    Requirement already satisfied: pyqt5 in /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages (5.15.0)
    Requirement already satisfied: PyQt5-sip<13,>=12.8 in /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages (from pyqt5) (12.8.0)

I don't know what else to do since the results from googling this problem only recommend to install the packages I'd already installed.

Even the out-of-date `pyside` - package is installed at some places on my system, even though I use linux-brew:

<details><summary>Click to open the results</summary>
<p>

```
    andylu@andylu-ThinkPad-Edge-E130:~/Desktop/Python/Scripts/General$ sudo find / -iname "*pyside*"
    find: ‘/run/user/1000/gvfs’: Permission denied
    find: ‘/tmp/.mount_pcloudgeFVGR’: Permission denied
    /snap/core/9436/usr/lib/python3/dist-packages/pyudev/__pycache__/pyside.cpython-35.pyc
    /snap/core/9436/usr/lib/python3/dist-packages/pyudev/pyside.py
    /snap/core/9665/usr/lib/python3/dist-packages/pyudev/__pycache__/pyside.cpython-35.pyc
    /snap/core/9665/usr/lib/python3/dist-packages/pyudev/pyside.py
    /snap/core18/1880/usr/lib/python3/dist-packages/pyudev/__pycache__/pyside.cpython-36.pyc
    /snap/core18/1880/usr/lib/python3/dist-packages/pyudev/pyside.py
    /snap/core18/1754/usr/lib/python3/dist-packages/pyudev/__pycache__/pyside.cpython-36.pyc
    /snap/core18/1754/usr/lib/python3/dist-packages/pyudev/pyside.py
    /usr/share/lintian/overrides/libpyside-py3-1.2
    /usr/share/lintian/overrides/python-pyside.qtopengl
    /usr/share/lintian/overrides/python-pyside.qtsql
    /usr/share/lintian/overrides/python-pyside.qttest
    /usr/share/lintian/overrides/python-pyside.qtuitools
    /usr/share/lintian/overrides/python-pyside.qtscript
    /usr/share/lintian/overrides/libpyside1.2
    /usr/share/lintian/overrides/python-pyside.qtgui
    /usr/share/lintian/overrides/python-pyside.phonon
    /usr/share/lintian/overrides/python-pyside.qtnetwork
    /usr/share/lintian/overrides/python-pyside.qthelp
    /usr/share/lintian/overrides/python-pyside.qtwebkit
    /usr/share/lintian/overrides/python-pyside.qtdeclarative
    /usr/share/lintian/overrides/python-pyside.qtxml
    /usr/share/lintian/overrides/python-pyside.qtcore
    /usr/share/lintian/overrides/python-pyside.qtsvg
    /usr/share/doc/python3-pyside.qtsql
    /usr/share/doc/python3-pyside.qtopengl
    /usr/share/doc/libpyside-py3-1.2
    /usr/share/doc/python-pyside.qtopengl
    /usr/share/doc/python3-pyside.qtsvg
    /usr/share/doc/python-pyside.qtsql
    /usr/share/doc/python-pyside.qttest
    /usr/share/doc/python-pyside.qtuitools
    /usr/share/doc/python-pyside.qtscript
    /usr/share/doc/libpyside1.2
    /usr/share/doc/python-pyside.qtgui
    /usr/share/doc/python3-pyside.qtxml
    /usr/share/doc/python3-pyside.qtuitools
    /usr/share/doc/python3-pyside.qttest
    /usr/share/doc/python-pyside.phonon
    /usr/share/doc/python-pyside.qtnetwork
    /usr/share/doc/python3-pyside.phonon
    /usr/share/doc/python3-pyside
    /usr/share/doc/python3-pyside.qtcore
    /usr/share/doc/python-pyside
    /usr/share/doc/python-pyside.qthelp
    /usr/share/doc/python3-pyside.qtgui
    /usr/share/doc/python-pyside.qtwebkit
    /usr/share/doc/python3-pyside.qtwebkit
    /usr/share/doc/python3-pyside.qtnetwork
    /usr/share/doc/python3-pyside.qthelp
    /usr/share/doc/python-pyside.qtdeclarative
    /usr/share/doc/python3-pyside.qtdeclarative
    /usr/share/doc/python-pyside.qtxml
    /usr/share/doc/python-pyside.qtcore
    /usr/share/doc/python3-pyside.qtscript
    /usr/share/doc/python-pyside.qtsvg
    /usr/lib/python3/dist-packages/PySide
    /usr/lib/python3/dist-packages/pyudev/pyside.py
    /usr/lib/python3/dist-packages/pyudev/__pycache__/pyside.cpython-36.pyc
    /usr/lib/x86_64-linux-gnu/libpyside.cpython-36m-x86_64-linux-gnu.so.1.2.2
    /usr/lib/x86_64-linux-gnu/libpyside.cpython-36m-x86_64-linux-gnu.so.1.2
    /usr/lib/x86_64-linux-gnu/libpyside-python2.7.so.1.2.2
    /usr/lib/x86_64-linux-gnu/libpyside-python2.7.so.1.2
    /usr/lib/python2.7/dist-packages/PySide.egg-info
    /usr/lib/python2.7/dist-packages/PySide
    /var/lib/dpkg/info/libpyside-py3-1.2:amd64.list
    /var/lib/dpkg/info/libpyside1.2:amd64.list
    /var/lib/dpkg/info/python3-pyside.qtcore.list
    /var/lib/dpkg/info/python-pyside.qtcore.list
    /var/lib/dpkg/info/python3-pyside.qtgui:amd64.list
    /var/lib/dpkg/info/python-pyside.qtgui.list
    /var/lib/dpkg/info/python3-pyside.phonon:amd64.list
    /var/lib/dpkg/info/python3-pyside.qtnetwork:amd64.list
    /var/lib/dpkg/info/python3-pyside.qtdeclarative:amd64.list
    /var/lib/dpkg/info/python-pyside.phonon.list
    /var/lib/dpkg/info/python-pyside.qtnetwork.list
    /var/lib/dpkg/info/python3-pyside.qthelp:amd64.list
    /var/lib/dpkg/info/python-pyside.qtdeclarative.list
    /var/lib/dpkg/info/python3-pyside.qtopengl:amd64.list
    /var/lib/dpkg/info/python-pyside.qthelp.list
    /var/lib/dpkg/info/python3-pyside.qtscript:amd64.list
    /var/lib/dpkg/info/python-pyside.qtopengl.list
    /var/lib/dpkg/info/python-pyside.qtscript.list
    /var/lib/dpkg/info/python3-pyside.qtsql:amd64.list
    /var/lib/dpkg/info/python-pyside.qtsql.list
    /var/lib/dpkg/info/python3-pyside.qtsvg:amd64.list
    /var/lib/dpkg/info/python-pyside.qtsvg.list
    /var/lib/dpkg/info/python3-pyside.qttest:amd64.list
    /var/lib/dpkg/info/python-pyside.qttest.list
    /var/lib/dpkg/info/python-pyside.qtxml.list
    /var/lib/dpkg/info/python3-pyside.qtxml:amd64.list
    /var/lib/dpkg/info/python-pyside.qtuitools.list
    /var/lib/dpkg/info/python3-pyside.qtuitools:amd64.list
    /var/lib/dpkg/info/python3-pyside.qtwebkit:amd64.list
    /var/lib/dpkg/info/python-pyside.qtwebkit.list
    /var/lib/dpkg/info/python-pyside.list
    /var/lib/dpkg/info/python3-pyside.list
    /var/lib/dpkg/info/libpyside-py3-1.2:amd64.md5sums
    /var/lib/dpkg/info/libpyside-py3-1.2:amd64.shlibs
    /var/lib/dpkg/info/libpyside-py3-1.2:amd64.symbols
    /var/lib/dpkg/info/libpyside-py3-1.2:amd64.triggers
    /var/lib/dpkg/info/python3-pyside.qtcore.md5sums
    /var/lib/dpkg/info/python3-pyside.qtcore.postinst
    /var/lib/dpkg/info/python3-pyside.qtcore.prerm
    /var/lib/dpkg/info/python3-pyside.qtgui:amd64.md5sums
    /var/lib/dpkg/info/python3-pyside.phonon:amd64.md5sums
    /var/lib/dpkg/info/python3-pyside.qtnetwork:amd64.md5sums
    /var/lib/dpkg/info/python3-pyside.qtdeclarative:amd64.md5sums
    /var/lib/dpkg/info/python3-pyside.qthelp:amd64.md5sums
    /var/lib/dpkg/info/python3-pyside.qtopengl:amd64.md5sums
    /var/lib/dpkg/info/python3-pyside.qtscript:amd64.md5sums
    /var/lib/dpkg/info/python3-pyside.qtsql:amd64.md5sums
    /var/lib/dpkg/info/python3-pyside.qtsvg:amd64.md5sums
    /var/lib/dpkg/info/python3-pyside.qttest:amd64.md5sums
    /var/lib/dpkg/info/python3-pyside.qtxml:amd64.md5sums
    /var/lib/dpkg/info/python3-pyside.qtuitools:amd64.md5sums
    /var/lib/dpkg/info/python3-pyside.qtwebkit:amd64.md5sums
    /var/lib/dpkg/info/python3-pyside.md5sums
    /var/lib/dpkg/info/libpyside1.2:amd64.md5sums
    /var/lib/dpkg/info/libpyside1.2:amd64.shlibs
    /var/lib/dpkg/info/libpyside1.2:amd64.symbols
    /var/lib/dpkg/info/libpyside1.2:amd64.triggers
    /var/lib/dpkg/info/python-pyside.qtcore.md5sums
    /var/lib/dpkg/info/python-pyside.qtcore.postinst
    /var/lib/dpkg/info/python-pyside.qtcore.prerm
    /var/lib/dpkg/info/python-pyside.qtgui.md5sums
    /var/lib/dpkg/info/python-pyside.phonon.md5sums
    /var/lib/dpkg/info/python-pyside.qtnetwork.md5sums
    /var/lib/dpkg/info/python-pyside.qtdeclarative.md5sums
    /var/lib/dpkg/info/python-pyside.qthelp.md5sums
    /var/lib/dpkg/info/python-pyside.qtopengl.md5sums
    /var/lib/dpkg/info/python-pyside.qtscript.md5sums
    /var/lib/dpkg/info/python-pyside.qtsql.md5sums
    /var/lib/dpkg/info/python-pyside.qtsvg.md5sums
    /var/lib/dpkg/info/python-pyside.qttest.md5sums
    /var/lib/dpkg/info/python-pyside.qtxml.md5sums
    /var/lib/dpkg/info/python-pyside.qtuitools.md5sums
    /var/lib/dpkg/info/python-pyside.qtwebkit.md5sums
    /var/lib/dpkg/info/python-pyside.md5sums
    find: ‘/home/andylu/pCloudDrive’: Permission denied
    /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pyside.rb
    /home/linuxbrew/.linuxbrew/bin/pyside2-lupdate
    /home/linuxbrew/.linuxbrew/bin/pyside2-designer
    /home/linuxbrew/.linuxbrew/bin/pyside2-uic
    /home/linuxbrew/.linuxbrew/bin/pyside2-rcc
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2-5.15.0.dist-info
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/shiboken2/docs/shiboken2/_static/pyside.css
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/shiboken2/docs/shiboken2/_static/pysidelogo.png
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/pyside2-lupdate
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/scripts/pyside_tool.py
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/scripts/__pycache__/pyside_tool.cpython-38.pyc
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/examples/scriptableapplication/pyside2.pri
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/examples/utils/__pycache__/pyside2_config.cpython-38.pyc
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/examples/utils/pyside2_config.py
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/_git_pyside_version.py
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/libpyside2.abi3.so.5.15
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/__pycache__/_git_pyside_version.cpython-38.pyc
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/Qt3DAnimation/pyside2_qt3danimation_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtMultimediaWidgets/pyside2_qtmultimediawidgets_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtXmlPatterns/pyside2_qtxmlpatterns_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/pysideweakref.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtGui/pyside2_qtgui_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtConcurrent/pyside2_qtconcurrent_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/pysidemacros.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtNetwork/pyside2_qtnetwork_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtQml/pyside2_qtqml_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtWidgets/pyside2_qtwidgets_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/pysideqflags.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtMultimedia/pyside2_qtmultimedia_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/Qt3DCore/pyside2_qt3dcore_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtWebChannel/pyside2_qtwebchannel_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtSensors/pyside2_qtsensors_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtUiTools/pyside2_qtuitools_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/pysidestaticstrings.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtWebEngineWidgets/pyside2_qtwebenginewidgets_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtWebEngine/pyside2_qtwebengine_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtPositioning/pyside2_qtpositioning_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtOpenGL/pyside2_qtopengl_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/pyside2_global.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtScxml/pyside2_qtscxml_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtHelp/pyside2_qthelp_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/Qt3DExtras/pyside2_qt3dextras_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtScript/pyside2_qtscript_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtQuickWidgets/pyside2_qtquickwidgets_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/pyside.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/Qt3DRender/pyside2_qt3drender_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtScriptTools/pyside2_qtscripttools_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtSvg/pyside2_qtsvg_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtPrintSupport/pyside2_qtprintsupport_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/Qt3DInput/pyside2_qt3dinput_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtWebSockets/pyside2_qtwebsockets_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtCharts/pyside2_qtcharts_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtTextToSpeech/pyside2_qttexttospeech_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/pysidesignal.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtSerialPort/pyside2_qtserialport_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtCore/pyside2_qtcore_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/pysideproperty.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtTest/pyside2_qttest_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtOpenGLFunctions/pyside2_qtopenglfunctions_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/pysidemetafunction.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtSql/pyside2_qtsql_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtQuick/pyside2_qtquick_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtQuickControls2/pyside2_qtquickcontrols2_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/Qt3DLogic/pyside2_qt3dlogic_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtDataVisualization/pyside2_qtdatavisualization_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtLocation/pyside2_qtlocation_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtX11Extras/pyside2_qtx11extras_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtXml/pyside2_qtxml_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/pysideclassinfo.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtRemoteObjects/pyside2_qtremoteobjects_python.h
    /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/PySide2/include/QtWebEngineCore/pyside2_qtwebenginecore_python.h
```

</p>
</details>

I wonder whether pointing to one of these `pyside` scripts outside of the `linux-brew site-packages` might be a good idea, or whether there are better solutions.

**Comment by AndreasLuckert** [comment]
I added this line to my `.bashrc` and `.bash_profile` files:

`export PYTHONPATH="/usr/lib/python3/dist-packages:$PYTHONPATH"`

Now, the package `PySide` can be imported since it was installed there, but cannot be installed via pip (which would lead to an installation in `/home/linuxbrew/.linuxbrew/lib/python3.8/site-packages`. With `pip`, it's only possible to install the latest version `Pyside2`.

Next, the error changed to `ModuleNotFoundError: No module named 'PySide.QtCore'`.

I could solve this issue then with `sudo ln -s QtCore.cpython-36m-x86_64-linux-gnu.so QtCore.so` executed from the directory `/usr/lib/python3/dist-packages/PySide`.

Now, my remaining problem is the following error:
```
User:~/$ jupyter qtconsole
/home/linuxbrew/.linuxbrew/opt/python@3.8/bin/python3.8: Relink `/usr/lib/x86_64-linux-gnu/libQtCore.so.4' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
Segmentation fault (core dumped)
```


_My system details are (if more are needed, please let me know):_

- **Python version:**
Python 3.8.5 (default, Jul 22 2020, 18:54:26) 
[GCC 5.4.0 20160609] on linux

- **OS:**
Linux Lubuntu 18.04 LTS

- User:~/$ **jupyter --version**
```
jupyter core     : 4.6.3
jupyter-notebook : 6.1.1
qtconsole        : 4.7.5
ipython          : 7.17.0
ipykernel        : 5.3.4
jupyter client   : 6.1.6
jupyter lab      : not installed
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.7
traitlets        : 4.3.3
```
