### ISSUE TITLE
Unable to launch qtconsole

### ISSUE THREAD

**Issue by stevenleeS0ht** [jupyter/qtconsole#496]
when starting `jupyter qtconsole`, the following Exception traceback provided,

```python3
Traceback (most recent call last):
  File "/usr/bin/jupyter-qtconsole", line 33, in <module>
    sys.exit(load_entry_point('qtconsole==5.1.1', 'gui_scripts', 'jupyter-qtconsole')())
  File "/usr/lib/python3.9/site-packages/qtconsole/qtconsoleapp.py", line 462, in main
    JupyterQtConsoleApp.launch_instance()
  File "/usr/lib/python3.9/site-packages/jupyter_core/application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/lib/python3.9/site-packages/traitlets/config/application.py", line 844, in launch_instance
    app.initialize(argv)
  File "/usr/lib/python3.9/site-packages/traitlets/config/application.py", line 87, in inner
    return method(app, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/qtconsole/qtconsoleapp.py", line 433, in initialize
    self.init_qt_elements()
  File "/usr/lib/python3.9/site-packages/qtconsole/qtconsoleapp.py", line 293, in init_qt_elements
    self.window.init_menu_bar()
  File "/usr/lib/python3.9/site-packages/qtconsole/mainwindow.py", line 382, in init_menu_bar
    self.init_view_menu()
  File "/usr/lib/python3.9/site-packages/qtconsole/mainwindow.py", line 622, in init_view_menu
    available_syntax_styles = self.get_available_syntax_styles()
  File "/usr/lib/python3.9/site-packages/qtconsole/mainwindow.py", line 795, in get_available_syntax_styles
    styles = list(get_all_styles())
  File "/usr/lib/python3.9/site-packages/pygments/styles/__init__.py", line 88, in get_all_styles
    for name, _ in find_plugin_styles():
  File "/usr/lib/python3.9/site-packages/pygments/plugin.py", line 63, in find_plugin_styles
    for entrypoint in iter_entry_points(STYLE_ENTRY_POINT):
  File "/usr/lib/python3.9/site-packages/pygments/plugin.py", line 45, in iter_entry_points
    import pkg_resources
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'debugpy<2.0,>=1.0.0' distribution was not found and is required by ipykernel
```

**Comment by wmvanvliet** [comment]
you need to install the debugpy package. The latest version of ipykernel depends on it. `pip install debugpy`.

**Comment by evan0greenup** [comment]
@stevenleeS0ht , It seems that the ipykernel you use is installed as a system package of your distribution.
The dependency is not quite updated.

I also have the same problem.
