### ISSUE TITLE
zmq error when exit qtconsole

### ISSUE THREAD

**Issue by AchmadFathoni** [jupyter/qtconsole#533]
**Step to reproduce**
1. Create poetry virtual environment
2. `$ poetry shell`
3. `$ poetry add qtconsole pyqt5`
4. `$ python -m jupyter qtconsole`
5. Exit qtconsole

**Error detail**
```
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(28, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(28, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/toni/.cache/pypoetry/virtualenvs/test-cxp6adJt-py3.10/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/toni/.cache/pypoetry/virtualenvs/test-cxp6adJt-py3.10/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 445, in _handle_events
    zmq_events = self.socket.EVENTS
  File "/home/toni/.cache/pypoetry/virtualenvs/test-cxp6adJt-py3.10/lib/python3.10/site-packages/zmq/sugar/attrsettr.py", line 51, in __getattr__
    return self._get_attr_opt(upper_key, opt)
  File "/home/toni/.cache/pypoetry/virtualenvs/test-cxp6adJt-py3.10/lib/python3.10/site-packages/zmq/sugar/attrsettr.py", line 63, in _get_attr_opt
    return self.get(opt)
  File "/home/toni/.cache/pypoetry/virtualenvs/test-cxp6adJt-py3.10/lib/python3.10/site-packages/zmq/_future.py", line 215, in get
    result = super(_AsyncSocket, self).get(key)
  File "zmq/backend/cython/socket.pyx", line 464, in zmq.backend.cython.socket.Socket.get
  File "zmq/backend/cython/socket.pyx", line 135, in zmq.backend.cython.socket._check_closed
zmq.error.ZMQError: Socket operation on non-socket
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(32, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(32, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/toni/.cache/pypoetry/virtualenvs/test-cxp6adJt-py3.10/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/toni/.cache/pypoetry/virtualenvs/test-cxp6adJt-py3.10/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 445, in _handle_events
    zmq_events = self.socket.EVENTS
  File "/home/toni/.cache/pypoetry/virtualenvs/test-cxp6adJt-py3.10/lib/python3.10/site-packages/zmq/sugar/attrsettr.py", line 51, in __getattr__
    return self._get_attr_opt(upper_key, opt)
  File "/home/toni/.cache/pypoetry/virtualenvs/test-cxp6adJt-py3.10/lib/python3.10/site-packages/zmq/sugar/attrsettr.py", line 63, in _get_attr_opt
    return self.get(opt)
  File "/home/toni/.cache/pypoetry/virtualenvs/test-cxp6adJt-py3.10/lib/python3.10/site-packages/zmq/_future.py", line 215, in get
    result = super(_AsyncSocket, self).get(key)
  File "zmq/backend/cython/socket.pyx", line 464, in zmq.backend.cython.socket.Socket.get
  File "zmq/backend/cython/socket.pyx", line 135, in zmq.backend.cython.socket._check_closed
zmq.error.ZMQError: Socket operation on non-socket
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(30, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(30, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/toni/.cache/pypoetry/virtualenvs/test-cxp6adJt-py3.10/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/toni/.cache/pypoetry/virtualenvs/test-cxp6adJt-py3.10/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 445, in _handle_events
    zmq_events = self.socket.EVENTS
  File "/home/toni/.cache/pypoetry/virtualenvs/test-cxp6adJt-py3.10/lib/python3.10/site-packages/zmq/sugar/attrsettr.py", line 51, in __getattr__
    return self._get_attr_opt(upper_key, opt)
  File "/home/toni/.cache/pypoetry/virtualenvs/test-cxp6adJt-py3.10/lib/python3.10/site-packages/zmq/sugar/attrsettr.py", line 63, in _get_attr_opt
    return self.get(opt)
  File "/home/toni/.cache/pypoetry/virtualenvs/test-cxp6adJt-py3.10/lib/python3.10/site-packages/zmq/_future.py", line 215, in get
    result = super(_AsyncSocket, self).get(key)
  File "zmq/backend/cython/socket.pyx", line 464, in zmq.backend.cython.socket.Socket.get
  File "zmq/backend/cython/socket.pyx", line 135, in zmq.backend.cython.socket._check_closed
zmq.error.ZMQError: Socket operation on non-socket
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(36, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(36, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/toni/.cache/pypoetry/virtualenvs/test-cxp6adJt-py3.10/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/toni/.cache/pypoetry/virtualenvs/test-cxp6adJt-py3.10/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 445, in _handle_events
    zmq_events = self.socket.EVENTS
  File "/home/toni/.cache/pypoetry/virtualenvs/test-cxp6adJt-py3.10/lib/python3.10/site-packages/zmq/sugar/attrsettr.py", line 51, in __getattr__
    return self._get_attr_opt(upper_key, opt)
  File "/home/toni/.cache/pypoetry/virtualenvs/test-cxp6adJt-py3.10/lib/python3.10/site-packages/zmq/sugar/attrsettr.py", line 63, in _get_attr_opt
    return self.get(opt)
  File "/home/toni/.cache/pypoetry/virtualenvs/test-cxp6adJt-py3.10/lib/python3.10/site-packages/zmq/_future.py", line 215, in get
    result = super(_AsyncSocket, self).get(key)
  File "zmq/backend/cython/socket.pyx", line 464, in zmq.backend.cython.socket.Socket.get
  File "zmq/backend/cython/socket.pyx", line 135, in zmq.backend.cython.socket._check_closed
zmq.error.ZMQError: Socket operation on non-socket
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(30, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(30, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/toni/.cache/pypoetry/virtualenvs/test-cxp6adJt-py3.10/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/toni/.cache/pypoetry/virtualenvs/test-cxp6adJt-py3.10/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 445, in _handle_events
    zmq_events = self.socket.EVENTS
  File "/home/toni/.cache/pypoetry/virtualenvs/test-cxp6adJt-py3.10/lib/python3.10/site-packages/zmq/sugar/attrsettr.py", line 51, in __getattr__
    return self._get_attr_opt(upper_key, opt)
  File "/home/toni/.cache/pypoetry/virtualenvs/test-cxp6adJt-py3.10/lib/python3.10/site-packages/zmq/sugar/attrsettr.py", line 63, in _get_attr_opt
    return self.get(opt)
  File "/home/toni/.cache/pypoetry/virtualenvs/test-cxp6adJt-py3.10/lib/python3.10/site-packages/zmq/_future.py", line 215, in get
    result = super(_AsyncSocket, self).get(key)
  File "zmq/backend/cython/socket.pyx", line 464, in zmq.backend.cython.socket.Socket.get
  File "zmq/backend/cython/socket.pyx", line 135, in zmq.backend.cython.socket._check_closed
zmq.error.ZMQError: Socket operation on non-socket

```

**Comment by ccordoba12** [comment]
Hey @AchmadFathoni, thanks for reporting. This is a problem in jupyter-client and it'll be fixed soon. See https://github.com/jupyter/jupyter_client/issues/771 for the discussion.
