### ISSUE TITLE
jupyter qtconsole --generate-config does not work

### ISSUE THREAD

**Issue by aweinstein** [jupyter/qtconsole#61]
Hi,

According to this documentation: http://jupyter.readthedocs.org/en/latest/config.html, you can do `jupyter {application} --generate-config` to create blank config files. `jupyter notebook --generate-config` does this: it creates the file `~/jupyter/jupyter_notebook_config.py`. However, I get an error with `jupyter qtconsole --generate-config` or `jupyter console --generate-config`. For instance:

```bash
jupyter qtconsole --generate-config
The Jupyter QtConsole.

This launches a Console-style application using Qt.  It is not a full console,
in that launched terminal subprocesses will not be able to accept input.

Options
-------

[...]

[JupyterQtConsoleApp] CRITICAL | Bad config encountered during initialization:
[JupyterQtConsoleApp] CRITICAL | Unrecognized flag: '--generate-config'
```

I'm runnig jupyter 4.0.6 (from anaconda).

P.D.: I'm having a hard time finding the right/preferred place to ask for help or discuss issues about jupyter (a mailing list, stackoverflow?). IPython.org has a "Community" and "For Developers" list of links at the right column. I can't see something similar for jupyter. It would be great if you can add something similar in jupyter.org.

**Comment by minrk** [comment]
Fixed by #52, will be released in 4.1 soon.

**Comment by minrk** [comment]
We are working on making the links more prominent as we get the new Jupyter into shape, but the jupyter mailing list [is on Google Groups](https://groups.google.com/forum/#!forum/jupyter).

**Comment by eric-wieser** [comment]
Fails for me with:
```
---------------------------
Error starting QtConsole
---------------------------
Traceback (most recent call last):
  File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\eriwiese\AppData\Roaming\Python\Python36\Scripts\jupyter-qtconsole.EXE\__main__.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\eriwiese\AppData\Roaming\Python\Python36\site-packages\qtconsole\qtconsoleapp.py", line 422, in main
    JupyterQtConsoleApp.launch_instance()
  File "C:\Users\eriwiese\AppData\Roaming\Python\Python36\site-packages\jupyter_core\application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\eriwiese\AppData\Roaming\Python\Python36\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\eriwiese\AppData\Roaming\Python\Python36\site-packages\qtconsole\qtconsoleapp.py", line 398, in start
    super(JupyterQtConsoleApp, self).start()
  File "C:\Users\eriwiese\AppData\Roaming\Python\Python36\site-packages\jupyter_core\application.py", line 259, in start
    self.write_default_config()
  File "C:\Users\eriwiese\AppData\Roaming\Python\Python36\site-packages\jupyter_core\application.py", line 141, in write_default_config
    answer = ask()
  File "C:\Users\eriwiese\AppData\Roaming\Python\Python36\site-packages\jupyter_core\application.py", line 137, in ask
    return raw_input(prompt).lower() or 'n'
RuntimeError: input(): lost sys.stdin

---------------------------
OK   
---------------------------
```
